audio/urls.py
from django.urls import path

from . import views

app_name = 'audio'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/edit/', views.edit, name='edit'),
    # path('<int:id>/update/', views.update, name='update'),
    # path('<int:id>/save/', views.save, name='save'),
    # path('<int:id>/delete/', views.delete, name='delete'),

    # path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('save/', views.save, name='save'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/process/', views.process, name='process'),
]

speechclassification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard'), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('grade/', include('grade.urls')),
    path('audio/', include('audio.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transcribe/urls.py
from django.urls import path

from . import views

app_name = 'transcribe'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/process/', views.process, name='process'),
]

transcribe/models.py
from django.db import models
from django.utils import timezone
from audio.models import File

# Create your models here.

class Transcribe(models.Model):
    File = models.ForeignKey(File, on_delete=models.CASCADE, null=True)
    # applicant_id = models.IntegerField(default=0) # in byte
    raw = models.TextField(default="")
    verbatim_text = models.TextField(default="")
    action_text = models.TextField(default="")
    enthusiasm_text = models.TextField(default="")
    focus_text = models.TextField(default="")
    imagine_text = models.TextField(default="")
    integrity_text = models.TextField(default="")
    smart_text = models.TextField(default="")
    solid_text = models.TextField(default="")
    speed_text = models.TextField(default="")
    totality_text = models.TextField(default="")
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.File

transcribe/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

from django.shortcuts import redirect
from django.core.files.storage import FileSystemStorage

from audio.models import File
from .models import Transcribe
from django.utils import timezone

from google.cloud import speech
from google.cloud import storage
import os


# bucket_name = 'kemitraan-telkom-1550985641715.appspot.com' #pak ikhsan
bucket_name = 'quantum-engine-248003.appspot.com' #pak ikhsan
# os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "sspk-owner.json" #pak ikhsan
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "credentials/My_First_Project-2c46ff0c115f.json" #pak ikhsan


def index(request):
    file_list = File.objects.all()
    context = {'file_list': file_list}
    return render(request, 'transcribe/index.html', context)


def edit(request, id):
    file = get_object_or_404(File, id=id)
    
    try:
        transcribe = Transcribe.objects.get(File_id=id)
    except Transcribe.DoesNotExist:
        transcribe = Transcribe.objects.create(File_id=file.id)

    context = {'file': file, 'transcribe': transcribe}
    return render(request, 'transcribe/edit.html', context)
    

def update(request, id):
    file = get_object_or_404(File, id=request.POST['id'])
    file.save()

    transcribe = get_object_or_404(Transcribe, File_id=request.POST['id'])
    # transcribe.action_text = request.POST['action_text']
    # transcribe.enthusiasm_text = request.POST['enthusiasm_text']
    # transcribe.focus_text = request.POST['focus_text']
    # transcribe.imagine_text = request.POST['imagine_text']
    # transcribe.integrity_text = request.POST['integrity_text']
    # transcribe.smart_text = request.POST['smart_text']
    # transcribe.solid_text = request.POST['solid_text']
    # transcribe.speed_text = request.POST['speed_text']
    # transcribe.totality_text = request.POST['totality_text']
    transcribe.verbatim_text = request.POST['verbatim_text']
    transcribe.updated_at = timezone.now()
    transcribe.save()

    return HttpResponseRedirect(reverse('transcribe:edit', args=(file.id,)))


def save(request):
    return redirect('/transcribe/')

def delete(request, id):
    return HttpResponse("You're voting on audio delete %s." % id)

def process(request, id):

    file = get_object_or_404(File, id=id)
    TranscribeThread.run(file)
    return HttpResponseRedirect(reverse('transcribe:edit', args=(id,)))

import threading
class TranscribeThread(threading.Thread):
    def run(file):
        try:
            hasil_transcribe = transcriptingstreo('gs://'+bucket_name+'/'+file.name)
        except:
            hasil_transcribe = transcriptingmono('gs://'+bucket_name+'/'+file.name)

        try:
            transcribe = Transcribe.objects.get(File_id=file.id)
        except Transcribe.DoesNotExist:
            transcribe = Transcribe.objects.create(File_id=file.id)

        transcribe.raw = hasil_transcribe
        transcribe.verbatim_text = hasil_transcribe
        transcribe.save()

def transcriptingstreo(filename):
    ##global hasiltranscript
    hasiltranscript=''
    #client=speech.SpeechClient()
    #audio=speech.types.RecognitionAudio(uri=filename)
    #config=speech.types.RecognitionConfig(
    #    encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,language_code='id-ID',audio_channel_count=2,
    #enable_separate_recognition_per_channel=True
    #)
    operation=speech.SpeechClient().long_running_recognize(
        config=speech.types.RecognitionConfig(encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,
        language_code='id-ID',audio_channel_count=2,enable_separate_recognition_per_channel=True)
        ,audio=speech.types.RecognitionAudio(uri=filename))
    print('Waiting for transcriptingstreo to complete...')
    #response = operation.result(timeout=10000)
    for result in operation.result(timeout=10000).results:
           hasiltranscript += str(result.alternatives[0].transcript)
    return hasiltranscript

def transcriptingmono(filename):
    #global hasiltranscript
    #client = speech.SpeechClient()
    #audio = speech.types.RecognitionAudio(uri=filename)
    #config = speech.types.RecognitionConfig(
    #    encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16, language_code='id-ID'
    #)
    #operation = client.long_running_recognize(config=config, audio=audio)
    hasiltranscript = ''
    operation = speech.SpeechClient().long_running_recognize(
        config=speech.types.RecognitionConfig(encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,
                                              language_code='id-ID')
        , audio=speech.types.RecognitionAudio(uri=filename))
    print('Waiting for transcriptingmono to complete...')
    response = operation.result(timeout=10000)
    for result in response.results:
        hasiltranscript += str(result.alternatives[0].transcript)

    return hasiltranscript

templates/transcribe/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<!-- third party css -->
<link href="{% static 'libs/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/select.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
<!-- third party css end -->

<!-- Footable css -->
<link href="{% static 'libs/footable/footable.core.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">File List</h4>
                            <p></p>
                            <table id="state-saving-datatable" class="table activate-select dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <!-- <th>Aplicant Name</th> -->
                                        <th>Upload Date</th>
                                        <th>File Name</th>
                                        <!-- <th>Upload Date</th> -->
                                        <th>Action</th>

                                        <!--<th>Full Text</th>-->
                                    </tr>
                                </thead>

                                <tbody>

                                    {% for file in file_list %}
                                    <tr>
                                        <!-- <td>{{ file.Applicant }}</td> -->
                                        <td>{{ file.created_at }}</td>
                                        <td>{{ file.name }}</td>
                                        <!-- <td>{{text.upload_date}}</td> -->
                                        <td>
                                            <a href="{% url 'transcribe:edit' file.id %}">
                                                <button type="button" class="ladda-button btn btn-success"
                                                    data-style="slide-right"><i class="mdi mdi-square-edit-outline"></i>
                                                    Edit
                                                </button>
                                            </a>

                                            <a href="{% url 'transcribe:process' file.id %}">
                                                <button type="button" class="ladda-button btn btn-danger"
                                                    data-style="slide-right"><i class="mdi mdi-play-box-outline"></i>
                                                    Transcribe</button>
                                            </a>

                                        </td>

                                        <!--<td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed neque vel massa molestie tempus at in eros. Ut sed augue ac ante bibendum efficitur ac eget lectus. In vulputate justo nec mollis gravida. Aliquam tristique tincidunt elementum. Maecenas cursus mauris sit amet rhoncus semper. Suspendisse a augue at eros eleifend consequat nec volutpat purus. Aenean viverra viverra est sed sodales. Donec porta enim quis sem lacinia, ac ullamcorper tortor sodales. Maecenas pharetra tincidunt augue non varius. Nunc euismod ut ipsum quis porta. Sed tristique eros sed urna dictum, varius ultricies nulla vehicula. In posuere lectus nec mollis ultricies. Morbi semper ligula ac nibh tempor auctor. Ut varius posuere mi, ut dapibus ipsum cursus non. Aliquam non sapien sed nulla elementum suscipit ac ut nisi.</td>-->
                                    </tr>
                                    {% endfor %}
                                    <!--<tr>
                                    <td>Mark Jurcas</td>
                                    <td>Senior Marketing Designer</td>
                                    <td>London</td>
                                    <td>43</td>
                                    <td>2012/12/18</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>
                                <tr>
                                    <td>Jacob Bima</td>
                                    <td>Regional Director</td>
                                    <td>London</td>
                                    <td>19</td>
                                    <td>2010/03/17</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>
                                <tr>
                                    <td>Larry the Bird</td>
                                    <td>Marketing Designer</td>
                                    <td>London</td>
                                    <td>66</td>
                                    <td>2012/11/27</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>-->
                                </tbody>
                            </table>

                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- container -->

    </div> <!-- content -->

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

{% block js %}

<!-- third party js -->
<script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.flash.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.select.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/vfs_fonts.js' %}"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

{% endblock %}